# This is a basic workflow to help you get started with Actions
name: workflow
# Controls when the workflow will run
  # Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:
    tags:
      - "pre-*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/setup-nasm@v1.3.1
      - name: Compilation
        run: nasm boot.asm -f bin -o boot.bin
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "pre-0.0.4"
          prerelease: true
          title: "pre-*"
          files: boot.bin
